import React, {useMemo, useRef, useState} from 'react';
import ReactDOM from 'react-dom/client';
import { SeqViz } from 'seqviz';
import './styles.css';
import { clean, stats, rc } from './sequenceUtils.js';
import { validateAnnotation, toFasta, parseFasta, makeProjectObject, parseProjectObject, makeSbolObject, parseSbolObject } from './projectUtils.js';

const EXAMPLE='ATGCGTACGTTAGCTAGCTAGGCTAACCGTTAGCGATCGATCGGATCCGATGCTAGCTAGCTAA';
const save=(name,data,type='text/plain')=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)};

function App(){
 const [project,setProject]=useState('My Synthetic Biology Project');
 const [sequence,setSequence]=useState(EXAMPLE);
 const [annotations,setAnnotations]=useState([{id:crypto.randomUUID(),name:'Example promoter',type:'Promoter',start:1,end:16,strand:'+',notes:'Demonstration annotation'}]);
 const [tab,setTab]=useState('editor'); const [dark,setDark]=useState(false); const [msg,setMsg]=useState('Ready'); const [tutorial,setTutorial]=useState(false);
 const [history,setHistory]=useState([EXAMPLE]); const [hIndex,setHIndex]=useState(0); const fileRef=useRef(); const st=useMemo(()=>stats(sequence),[sequence]);
 const commit=v=>{const n=clean(v),h=history.slice(0,hIndex+1);h.push(n);setSequence(n);setHistory(h);setHIndex(h.length-1);setMsg('Sequence updated')};
 const newProject=()=>{setProject('Untitled SBOL3 Project');setSequence('');setAnnotations([]);setHistory(['']);setHIndex(0);setMsg('New project created')};
 const loadExample=()=>{setProject('Example Genetic Construct');setSequence(EXAMPLE);setHistory([EXAMPLE]);setHIndex(0);setAnnotations([{id:crypto.randomUUID(),name:'Promoter',type:'Promoter',start:1,end:16,strand:'+',notes:'Example promoter region'},{id:crypto.randomUUID(),name:'Coding sequence',type:'CDS',start:17,end:48,strand:'+',notes:'Example coding region'}]);setMsg('Example loaded')};
 const undo=()=>{if(hIndex>0){setHIndex(hIndex-1);setSequence(history[hIndex-1]);setMsg('Undo completed')}};
 const redo=()=>{if(hIndex<history.length-1){setHIndex(hIndex+1);setSequence(history[hIndex+1]);setMsg('Redo completed')}};
 const exportFasta=()=>{save(`${project.replace(/\s+/g,'_')}.fasta`,toFasta(project,sequence));setMsg('FASTA exported')};
 const exportProject=()=>{save(`${project.replace(/\s+/g,'_')}.json`,JSON.stringify(makeProjectObject({projectName:project,sequence,annotations}),null,2),'application/json');setMsg('Project exported')};
 const exportSBOL=()=>{save(`${project.replace(/\s+/g,'_')}.sbol3.jsonld`,JSON.stringify(makeSbolObject({projectName:project,sequence,annotations}),null,2),'application/ld+json');setMsg('SBOL3 JSON-LD exported')};
 const importFile=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const t=String(r.result||'');if(f.name.toLowerCase().match(/\.(fa|fasta)$/)||t.startsWith('>')){const d=parseFasta(t);setProject(d.projectName);setSequence(d.sequence);setAnnotations([]);setHistory([d.sequence]);setHIndex(0);setMsg('FASTA imported');return;}const raw=JSON.parse(t);const d=raw.format==='SBOL3-Sequence-Editor-Project'?parseProjectObject(raw):parseSbolObject(raw);setProject(d.projectName);setSequence(d.sequence);setAnnotations(d.annotations);setHistory([d.sequence]);setHIndex(0);setMsg(raw.format==='SBOL3-Sequence-Editor-Project'?'Project imported':'SBOL3 imported');}catch(err){setMsg('Import failed: '+err.message)}finally{e.target.value=''}};r.readAsText(f)};
 const addAnnotation=e=>{e.preventDefault();const f=new FormData(e.currentTarget),start=+f.get('start'),end=+f.get('end');const validation=validateAnnotation({start,end},sequence.length);if(!validation.valid){setMsg(validation.error);return;}setAnnotations(a=>[...a,{id:crypto.randomUUID(),name:f.get('name'),type:f.get('type'),start,end,strand:f.get('strand'),notes:f.get('notes')}]);e.currentTarget.reset();setMsg('Annotation added')};
 const nav=[['dashboard','Dashboard'],['editor','DNA Editor'],['annotations','Annotation Manager'],['visualisation','Visualisation'],['analysis','Analysis'],['sbol','SBOL3 Manager']];
 return <div className={dark?'app dark':'app'}>
  <header className="topbar"><div><p className="eyebrow">Standards-aware synthetic biology workspace</p><h1>SBOL3 Sequence Editor</h1></div><div className="badge">JavaScript · React · SBOL3</div></header>
  <section className="toolbar">{[['Load Example',loadExample],['New Project',newProject],['Import FASTA / Project / SBOL3',()=>fileRef.current?.click()],['Export Project',exportProject],['Export SBOL3',exportSBOL],['Export FASTA',exportFasta],['Undo',undo],['Redo',redo],[dark?'Light Mode':'Dark Mode',()=>setDark(!dark)],['Tutorial',()=>setTutorial(true)]].map(([t,f])=><button key={t} onClick={f}>{t}</button>)}<input ref={fileRef} type="file" accept=".fasta,.fa,.json,.jsonld,.sbol" hidden onChange={importFile}/></section>
  <div className="workspace"><aside className="sidebar"><div className="brand"><div className="dna">DNA</div><div><strong>Project Workspace</strong><span>SBOL3 + SBOL Visual</span></div></div><nav>{nav.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav><div className="status"><strong>Project status</strong><span>{msg}</span></div></aside>
  <main><section className="hero"><div><p className="kicker">Current project</p><input value={project} onChange={e=>setProject(e.target.value)} /><p>Design, annotate, analyse and exchange DNA constructs in one browser-based environment.</p></div><div className="heroCode">ACGT</div></section>
  <section className="stats"><article><span>Sequence length</span><strong>{st.n}</strong><small>nucleotides</small></article><article><span>Annotations</span><strong>{annotations.length}</strong><small>biological features</small></article><article><span>GC content</span><strong>{st.gc}%</strong><small>G + C bases</small></article><article><span>Validation</span><strong>{sequence?'Valid':'Empty'}</strong><small>ACGTN alphabet</small></article></section>
  {tab==='dashboard'&&<section className="card"><p className="kicker">Project overview</p><h2>Welcome to your synthetic biology workspace</h2><div className="two"><ul><li>Edit and validate nucleotide sequences</li><li>Create biological annotations</li><li>Review nucleotide composition and GC content</li><li>Import and export FASTA, project JSON and SBOL3 JSON-LD</li><li>Prepare constructs for SBOL Visual rendering</li></ul><div className="highlight"><b>SBOL3-ready</b><h3>Interoperable biological design data</h3><p>The prototype maps project data to Component, Sequence and SequenceFeature objects.</p></div></div></section>}
  {tab==='editor'&&<section className="card"><div className="head"><div><p className="kicker">Core module</p><h2>DNA Editor</h2></div><button className="secondary" onClick={()=>commit(rc(sequence))}>Reverse complement</button></div><textarea value={sequence} onChange={e=>commit(e.target.value)} placeholder="Enter A, C, G, T or N" spellCheck="false"/><div className="bases">{Object.entries(st.c).map(([b,v])=><div key={b}><b>{b}</b><span>{v}</span></div>)}</div></section>}
  {tab==='annotations'&&<section className="card"><p className="kicker">Biological metadata</p><h2>Annotation Manager</h2><form onSubmit={addAnnotation}><label>Name<input name="name" required placeholder="e.g. lac promoter"/></label><label>Type<select name="type">{['Promoter','Gene','CDS','Terminator','RBS','Origin','Miscellaneous'].map(x=><option key={x}>{x}</option>)}</select></label><label>Start<input name="start" type="number" min="1" defaultValue="1" required/></label><label>End<input name="end" type="number" min="1" defaultValue={Math.max(1,sequence.length)} required/></label><label>Strand<select name="strand"><option value="+">Forward (+)</option><option value="-">Reverse (-)</option></select></label><label className="wide">Notes<input name="notes" placeholder="Optional description"/></label><button className="primary">Add annotation</button></form><div className="annList">{annotations.length?annotations.map(a=><article key={a.id}><div><span className="chip">{a.type}</span><h3>{a.name}</h3><p>Positions {a.start}–{a.end} · Strand {a.strand}</p><small>{a.notes}</small></div><button className="delete" onClick={()=>setAnnotations(x=>x.filter(i=>i.id!==a.id))}>Delete</button></article>):<p className="empty">No annotations yet.</p>}</div></section>}
  {tab==='visualisation'&&<section className="card"><p className="kicker">Interactive DNA viewer</p><h2>SeqViz Visualisation</h2>{sequence?<div className="seqvizShell"><SeqViz name={project} seq={sequence} viewer="both" showComplement={true} annotations={annotations.filter(a=>a.start>=1&&a.end<=sequence.length).map((a,i)=>({start:a.start-1,end:a.end,name:a.name,direction:a.strand==='-'?-1:1,color:['#6d4c7d','#8a674f','#a68b32','#557565','#8c557b'][i%5]}))} style={{height:'560px',width:'100%'}} /></div>:<p className="empty">Add or import a DNA sequence to activate SeqViz.</p>}<p className="muted">SeqViz renders the active sequence in linear and circular views. Annotation coordinates are converted from the editor's 1-based positions to SeqViz's 0-based ranges.</p></section>}
  {tab==='analysis'&&<section className="card"><p className="kicker">Real-time calculations</p><h2>Sequence Analysis</h2><div className="analysis"><article><span>GC content</span><strong>{st.gc}%</strong><div className="meter"><i style={{width:st.gc+'%'}}/></div></article><article><span>AT content</span><strong>{st.at}%</strong><div className="meter"><i style={{width:st.at+'%'}}/></div></article>{Object.entries(st.c).map(([b,v])=><article key={b}><span>{b} count</span><strong>{v}</strong><small>{st.n?((v/st.n)*100).toFixed(2):'0.00'}%</small></article>)}</div></section>}
  {tab==='sbol'&&<section className="card"><p className="kicker">Standards manager</p><h2>SBOL3 Manager</h2><div className="two"><div><p>Current project data is mapped to a Component, Sequence and SequenceFeature collection.</p><button className="primary" onClick={exportSBOL}>Export SBOL3 JSON-LD</button></div><pre>{JSON.stringify({component:project,sequenceLength:st.n,featureCount:annotations.length,encoding:'IUPAC DNA',format:'SBOL3 JSON-LD'},null,2)}</pre></div></section>}
  </main></div><footer><span>SBOL3 Sequence Editor</span><span>React · JavaScript · HTML5 · CSS3</span></footer>
  {tutorial&&<div className="modal"><section><button className="close" onClick={()=>setTutorial(false)}>×</button><p className="kicker">Quick tutorial</p><h2>Build your first DNA construct</h2><ol><li>Create a new project or load the example.</li><li>Edit DNA using A, C, G, T or N.</li><li>Add biological features.</li><li>Review visualisation and analysis.</li><li>Export FASTA, project JSON or SBOL3 JSON-LD.</li></ol><button className="primary" onClick={()=>setTutorial(false)}>Start editing</button></section></div>}
 </div>
}
ReactDOM.createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
